### ISSUE TITLE
No work 

### ISSUE THREAD

**Issue by DraidS** [Firebladedoge229/MidiExporter#2]
Uhm icon is blank page not open  i did that thing in cmd and it give error what do i install pls help

**Comment by DraidS** [comment]
Please

**Comment by DraidS** [comment]
Quick

**Comment by Firebladedoge229** [comment]
??

**Comment by DraidS** [comment]
https://cdn.discordapp.com/attachments/1135578652189405224/1233894750910808177/image.png?ex=662ec189&is=662d7009&hm=84fec920efe739c62c31ccaea002634ad02ba9ce9e14157cf0b5bafb5d53ce0f&

**Comment by DraidS** [comment]
![image](https://github.com/Firebladedoge229/MidiExporter/assets/111546975/17a69ac5-7a3b-450a-85f4-da5fb81bb640)

**Comment by DraidS** [comment]
virus!!

**Comment by DraidS** [comment]
my pc is bajilion year old
no fooling me i has windows 10

**Comment by Firebladedoge229** [comment]
no information

**Comment by DraidS** [comment]
This is fake It give me virus owner has virus!!

**Comment by DraidS** [comment]
I will be reporting to github!!

**Comment by DraidS** [comment]
This guy is fake

**Comment by DraidS** [comment]
e

**Comment by DraidS** [comment]
e

**Comment by DraidS** [comment]
e

**Comment by Firebladedoge229** [comment]
QUIT YAPPING PLEASE

**Comment by DraidS** [comment]
STOP GIVING ME VIRUS

**Comment by DraidS** [comment]
NUH UH

**Comment by DraidS** [comment]
STOP

**Comment by DraidS** [comment]
appas

**Comment by DraidS** [comment]
e
